### PR TITLE
Serialize And Deserialize Binary Tree (BFS)

### PR DESCRIPTION
**Pull request by maximderbin**

### CODE REVIEW

**Comment by maximderbin** [comment]
@dmitriiabramov could you review this shit?

**Comment by maximderbin** [comment]
@dmitriiabramov do you know better approach?

**Comment by boujeepossum** [comment]
that's the simplest way.
other ways to look at are: nested sets, adjacency list, path enum

**Comment by boujeepossum** [comment]
your way is not the most efficient, because it has a bunch of `null`s in the datastructure

**Pull request merged**
